### ISSUE TITLE
Duplicate species in input files

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/vibi#10]
How should the system handle duplicate species in input files?

**Comment by jreinier** [comment]
If I remember correctly, the problem was associated with resubmitting a workbook with changes.  Would requiring the old workbook to be deleted before resubmitting solve the problem?

**Comment by Gnafu** [comment]
The issue is about records within the workbook: if we cannot uniquely identify records inside a single workbook, the update and the delete operations will not work properly.

**Comment by jreinier** [comment]
I think it would be best to add a sequential identifier to duplicate species to make them unique.  So for example if there were two entries for "Carex sp.", then upon ingestion those would become "Carex sp.1" and "Carex sp.2."  Obviously we would need to add records to the species table for every "sp." case.  My question is:  Is there any way to add the sequential identifier on the fly during ingestion, or will the workbooks need to be changed prior to ingestion?  The task of going through all 400 existing plots and changing every duplicate would be very time consuming.

**Comment by Gnafu** [comment]
The de-duplication can happen on the server side, the only thing to note is this: if you need to update de-duplicated records, the original rows order in the updated spreadsheet should now change.

**Comment by Gnafu** [comment]
I edited the previous comment, there is no need to keep the input spreadsheets ordering.

**Comment by jreinier** [comment]
Great. I uploaded a new species table with 'sp." identifiers 1-10 for testing at:
https://github.com/jreinier/vibi.
